sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stephengrider/react-test npm test

after_success:
  - docker build -t 2dazed/multi-client ./client
  - docker build -t 2dazed/multi-nginx ./nginx
  - docker build -t 2dazed/multi-server ./server
  - docker build -t 2dazed/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 2dazed/multi-client
  - docker push 2dazed/multi-nginx
  - docker push 2dazed/multi-server
  - docker push 2dazed/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-179783938766"
    bucket_path: "docker-multi"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
